version: '3.9'

services:
  jcosta_apache_php74:
    container_name: jcosta_apache_php74
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./www:/var/www/html
    ports:
      - 8080:80
      - 8000:8000
    links:
      - jcosta_mysql

  jcosta_mysql:
    image: mysql:5.7
    container_name: jcosta_mysql
    ports:
      - "3397:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=123
      - TZ=America/Sao_Paulo

networks:
  default:
    external:
      name: jcosta-network
